/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:9c9d81bf-f48f-4ef4-bf4e-250fa498993e",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_cxJuwwtZB",
    "aws_user_pools_web_client_id": "46eafqb62ucdo254ek492ioto4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://7noq2sxixjdxfnkxvk7j6pytdi.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
