/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:8d003aa2-c8c9-4142-98dd-0cee33fe8120",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_9lurYeR1q",
    "aws_user_pools_web_client_id": "72d3hqo4p1tdjnhtku95n2bljm",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://5rj4bfntbvfjznhj4u6v4jissm.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sxbbaczi4jfl7gen2uydwzacqe"
};


export default awsmobile;
